---
repos:
  - repo: local
    hooks:
      - id: generate-hosts-file
        name: Generate Hosts File
        entry: python3 pre-commit/generate_hosts_file.py
        language: python

      - id: generate-ssh-config
        name: Generate SSH Config
        entry: python3 pre-commit/generate_ssh_config.py
        language: python

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v6.22.2
    hooks:
      - id: ansible-lint
        args: ['--exclude', '.github']

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        language_version: python3.11
