---
- name: Run Prerequisites
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Execute Python script
      command: python3 tools/{{ item }}
      become: no
      loop:
        - generate_hosts_file.py
        - generate_ssh_config.py

- name: Configure Base
  hosts: default
  strategy: ansible.builtin.free
  become: true
  roles:
    - name: base

- name: Configure Docker
  hosts: docker
  strategy: free
  become: true
  roles:
    - name: docker

- name: Configure Production
  hosts: production
  become: true
  roles:
    - name: production

