---
- name: Configure Base
  hosts: default
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure plex host
  hosts: plex
  become: true
  vars_files:
    - roles/vault/defaults/main.yml
  roles:
    - role: plex
      tags: plex

- name: Configure nginx host
  hosts: webserver
  become: true
  roles:
    - role: nginx
      tags: nginx

- name: Configure Docker
  hosts: docker
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: docker
      tags: docker

- name: Configure gpu host
  hosts: gpu
  become: true
  roles:
    - role: gpu
      tags: gpu
