---
- name: Configure Base
  hosts: default
  strategy: "{{ strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure Docker
  hosts: docker
  become: true
  roles:
    - role: docker
      tags: docker

- name: Specific to rhel host
  ansible.builtin.import_playbook: plays/rhel.yml

- name: Specific to plex host
  ansible.builtin.import_playbook: plays/plex.yml
