---
- name: Configure Base
  hosts: default
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure Docker
  hosts: docker
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: docker
      tags: docker

- name: Configure plex host
  hosts: plex
  tasks:
    - name: Include nowplaying tasks
      ansible.builtin.import_tasks:
        file: tasks/nowplaying.yml
