---
- name: Configure Bridge
  hosts: bridge
  become: true
  roles:
    - name: base
    - name: docker

- name: Configure Webserver
  hosts: webserver
  become: true
  roles:
    - name: base
    - name: docker

- name: Configure Production
  hosts: production
  become: true
  roles:
    - name: base
    - name: docker
    - name: production

- name: Configure Plex
  hosts: plex
  become: true
  roles:
    - name: base

- name: Configure RTV Web
  hosts: romantv
  become: true
  roles:
    - name: base
    - name: docker

- name: Configure Jenkins
  hosts: jenkins
  become: true
  roles:
    - name: base

- name: Configure Vaultwarden
  hosts: vaultwarden
  become: true
  roles:
    - name: base
    - name: docker

- name: Configure Test server
  hosts: nuc
  become: true
  rolse:
    - name: base
    - name: docker

- name: Configure GPU
  hosts: gpu
  become: true
  rolse:
    - name: base
    - name: docker

- name: Configure Kubernetes server
  hosts: pbs
  become: true
  rolse:
    - name: base

- name: Configure Octopi
  hosts: octopi
  become: true
  rolse:
    - name: base

- name: Configure Proxmox
  hosts: proxmox
  become: true
  rolse:
    - name: base

- name: Configure Proxmox Backup Server
  hosts: pbs
  become: true
  rolse:
    - name: base

