---
- name: Configure Base
  hosts: default
  strategy: "{{ strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure Docker
  hosts: docker
  become: true
  roles:
    - role: docker
      tags: docker

- name: Configure additional
  hosts: default
  become: true
  roles:
    - role: additional
      tags: additional
