---
- name: Configure Base
  hosts: default
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure nginx host
  hosts: webserver
  become: true
  roles:
    - role: nginx
      tags: nginx

- name: Configure Docker
  hosts: docker
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: docker
      tags: docker

- name: Configure rhel host
  hosts: rhel
  tasks:
    - name: Include reboot-router cron tasks
      ansible.builtin.import_tasks:
        file: tasks/reboot-router-cron.yml

- name: Configure plex host
  hosts: plex
  tasks:
    - name: Include nowplaying tasks
      ansible.builtin.import_tasks:
        file: tasks/nowplaying.yml
