---
- name: Configure Base
  hosts: default
  strategy: free
  become: true
  roles:
    - name: base

- name: Configure Docker
  hosts: docker
  strategy: free
  become: true
  roles:
    - name: docker

- name: Configure Production
  hosts: prouction
  become: true
  roles:
    - name: production

