---
- name: Configure Base
  hosts: default
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: base
      tags: base

- name: Configure Docker
  hosts: docker
  strategy: "{{ ansible_strategy | default('ansible.builtin.linear') }}"
  become: true
  roles:
    - role: docker
      tags: docker

- name: Configure webserver
  hosts: webserver
  become: true
  roles:
    - role: webserver
      tags: webserver