version: "2.1"

services:
  heimdall:
    container_name: heimdall_rtv
    image: linuxserver/heimdall:2.5.8
    environment:
      - APP_NAME=RomanTV
    volumes:
      - ./heimdall:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`tv.romanpeters.nl`)"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:2.13.4
    container_name: tautulli
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - 8181:8181
    volumes:
      - ./tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.romanpeters.nl`)"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    ports:
      - 5055:5055
    volumes:
      - ./overseerr/config/:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Amsterdam
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`request.romanpeters.nl`)"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    restart: unless-stopped
