---
version: "3.7"

services:
  uptime:
    image: louislam/uptime-kuma:1.23.13
    container_name: "{{ service_name }}"
    volumes:
      - ./data:/app/data
    ports:
      - "{{ service_port }}:3001"
    restart: always
