---
version: "2.1"

services:
  heimdall:
    image: linuxserver/heimdall:2021.11.28
    container_name: heimdall_romanpeters.nl
    environment:
      - APP_NAME=romanpeters
    volumes:
      - ./heimdall:/config
    ports:
      - 3939:80
    restart: always
