---
- name: Clone Plex NowPlaying repository
  ansible.builtin.git:
    repo: https://github.com/arcadellama/plex-nowplaying.git
    dest: /tmp/plex-nowplaying
    update: true
  become: true
  become_user: "{{ username }}"
  register: git_clone_result

- name: Move nowplaying to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/plex-nowplaying/nowplaying
    dest: /usr/local/bin/
    remote_src: true
  become: true
  when: git_clone_result.rc == 0

- name: Create nowplaying config
  ansible.builtin.copy:
    src: /tmp/plex-nowplaying/nowplaying.conf.sample
    dest: /home/{{ username }}/.config/nowplaying.conf
    remote_src: true
  when: git_clone_result.rc == 0

- name: Set NP_PLEX_HOST in nowplaying.conf
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.config/nowplaying.conf
    regexp: ^#?(\s*)NP_PLEX_HOST\s*=\s*\S.*
    line: NP_PLEX_HOST=127.0.0.1

- name: Set NP_PLEX_PORT in nowplaying.conf
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.config/nowplaying.conf
    regexp: ^#?(\s*)NP_PLEX_PORT\s*=\s*\S.*
    line: NP_PLEX_PORT=32400

- name: Set NP_PLEX_TOKEN in nowplaying.conf
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.config/nowplaying.conf
    regexp: ^#?(\s*)NP_PLEX_TOKEN\s*=\s*\S.*
    line: NP_PLEX_TOKEN={{ plex_token }}

- name: Cleanup nowplaying
  ansible.builtin.file:
    path: /tmp/plex-nowplaying
    state: absent
