version: "2.1"

services:
  heimdall:
    container_name: heimdall_rtv
    image: linuxserver/heimdall:2021.11.28
    environment:
      - APP_NAME=RomanTV
    volumes:
      - ./heimdall:/config
    ports:
      - 3838:80
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`tv.romanpeters.nl`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=3838"

  tautulli:
    image: linuxserver/tautulli:2.13.4
    container_name: tautulli
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
    ports:
      - 8181:8181
    volumes:
      - ./tautulli:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`tautulli.romanpeters.nl`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=8181"

  overseerr:
    image: sctx/overseerr:1.33.2
    container_name: overseerr
    ports:
      - 5055:5055
    volumes:
      - ./overseerr/config/:/app/config
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Amsterdam
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`requests.romanpeters.nl`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=5055"
