---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.21-ls259
    container_name: {{ service_name }}
    environment:
      - PUID=1080
      - PGID=1080
      - TZ=Europe/Amsterdam
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - ./config:/config
      - /mnt/media/books/ebooks:/books
    ports:
      - {{ service_port }}:8083
    restart: always
