---
version: "3"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:2.11.3
    container_name: "{{ service_name }}"
    ports:
      - 80:80
      - "{{ service_port }}:81"
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    dns:
      - 1.1.1.1
      - 1.0.0.1
    restart: always
