- name: test nginx configuration
  ansible.builtin.command: nginx -t
  delegate_to: webserver
  listen: restart nginx

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
  delegate_to: webserver
  listen: restart nginx

- name: restart homer
  docker_container:
    name: homer
    image: b4bz/homer
    state: present
    restart: true

- name: restart fooocus
  systemd:
    name: fooocus
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart automatic1111
  systemd:
    name: automatic1111
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart whisper
  systemd:
    name: whisper
    daemon_reload: yes
    state: restarted
    enabled: yes
