---
services:
  traefik:
    image: "traefik:v3.1.6"
    container_name: "{{ service_name }}"
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.redis=true"
      - "--providers.redis.exposedByDefault=false"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "{{ service_port }}:8080"
    restart: unless-stopped
    labels:
      - "traefik.http.routers.traefik.rule=Host(`{{ service_name }}.romanpeters.nl`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port={{ service_port }}"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
