version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.30.1
    container_name: vaultwarden
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: 'true'
      SENDS_ALLOWED: 'true'
      LOG_FILE: /data/logs/bitwarden.log
      EXTENDED_LOGGING: 'false'
      LOG_LEVEL: 'warn'
      ADMIN_TOKEN: "{{ vaultwarden_admin_token }}"
    volumes:
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.romanpeters.nl`)"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"
      - "traefik.http.services.vaultwarden.loadbalancer.server.scheme=http"
    ports:
      - '3012:3012'  # websocket
      - '3011:80'
    restart: unless-stopped

