- name: Copy Nginx file {{ service_name }} to webserver
  ansible.builtin.template:
    src: nginx/site.j2
    dest: /etc/nginx/sites-available/{{ service_name }}.{{ domain }}
  delegate_to: webserver
  notify: restart nginx

- name: Create symlink to enable the {{ service_name }}
  file:
    src: /etc/nginx/sites-available/{{ service_name }}.{{ domain }}
    dest: /etc/nginx/sites-enabled/{{ service_name }}.{{ domain }}
    state: link
  delegate_to: webserver
  notify: restart nginx
