# MANAGED BY ANSIBLE
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git command-not-found zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

alias cd="zoxide"
alias ls="exa"
alias cat="bat"
alias df="duf"
alias grep="ripgrep"

echo
neofetch
PS1='%F{#808080}%D{%L:%M:%S} %B%F{#32cd32}[%F{#32cd32}%n%F{#80f000}%b@%B%F{#ff6666}%B%m%b%F{#32cd32} %F{#32cd32}%~%F{#32cd32}]%b${vcs_info_msg_0_}%f$ '
