# MANAGED BY ANSIBLE
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git command-not-found zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

alias ls="exa"
alias cat="batcat"
alias grep="rg"

echo
neofetch
PS1='%F{#808080}%D{%L:%M:%S} %B%F{#32cd32}[%F{#32cd32}%n%F{#80f000}%b@%B%F{#ff6666}%B%m%b%F{#32cd32} %F{#32cd32}%~%F{#32cd32}]%b${vcs_info_msg_0_}%f$ '

