---
services:
  homer:
    image: b4bz/homer
    container_name: "homer_ai"
    volumes:
      - ./assets/:/www/assets
    ports:
      - "80:8080"
    user: 1000:1000
    environment:
      - INIT_ASSETS=0
      - IPV6_DISABLE=1
