base_packages:
  - vim
  - neovim
  - git
  - acl
  - tmux
  - neofetch
  - lolcat
  - toilet
  - cowsay
  - sl
  - exa
  - ripgrep
  - tldr
  - command-not-found
  - trash-cli
  - btop
  - bat
  - duf
  - python3
  - python3-pip

dev_packages:
  - ansible
  - ansible-lint
  - pre-commit

