---
services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:0.14.0
    container_name: "{{ service_name }}"
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ./data/:/data/
    ports:
      - "{{ service_port }}:7745"
    restart: always
