---
- name: Playbook for RHEL host
  hosts: rhel
  vars_files:
    - group_vars/all.yml
  tasks:
    - name: Reboot router cronjob
      ansible.builtin.cron:
        name: reboot-router
        minute: "*/15"
        job: ping -c 2 1.1.1.1 > /dev/null 2>&1 || tower-cli job launch --job-template="reboot-router"
      delegate_to: "{{ username }}"
