---
services:
  adguardhome:
    image: adguard/adguardhome:v0.107.46
    container_name: "{{ service_name }}"
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - "{{ service_port }}:80/tcp"
    volumes:
      - ./work:/opt/adguardhome/work
      - ./conf:/opt/adguardhome/conf
    restart: always
