---
services:
  heimdall:
    image: linuxserver/heimdall:2021.11.28
    container_name: "{{ service_name }}"
    environment:
      - APP_NAME=romanpeters
    volumes:
      - ./heimdall:/config
    ports:
      - "{{ service_port }}:80"
    restart: always
