---
- name: Ensure Python dependencies
  ansible.builtin.pip:
    name:
      - requests
      - docker==6.1.3
      - docker-compose

- name: Ensure the directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/docker/{{ item }}"
    state: directory
  loop: "{{ docker_services }}"

- name: Find directories in /home/{{ username }}/docker/
  find:
    paths: "/home/{{ username }}/docker/"
    file_type: directory
  register: existing_docker_services

- name: Copy Docker Compose files
  ansible.builtin.copy:
    src: "docker/{{ item }}.yml"
    dest: /home/{{ username }}/docker/{{ item }}/docker-compose.yml
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ docker_services }}"

- name: Stop other containers
  community.docker.docker_compose:
    project_src: "{{ item.path }}"
    state: absent
  with_items: "{{ existing_docker_services.files }}"
  when: item.path.split('/') | last not in docker_services
  ignore_errors: true

- name: Start docker containers
  community.docker.docker_compose:
    project_src: /home/{{ username }}/docker/{{ item }}
    state: present
  loop: "{{ docker_services }}"

