---
- name: Ensure Python dependencies
  ansible.builtin.pip:
    name:
      - requests
      - docker==6.1.3
      - docker-compose

- name: Ensure the directory exists
  ansible.builtin.file:
    path: "/home/{{ username }}/docker/{{ item.name }}"
    state: directory
  loop: "{{ docker_services }}"

- name: Copy Docker Compose files
  ansible.builtin.copy:
    src: "{{ item.src | default(item.name) }}/docker-compose.yml"
    dest: /home/{{ username }}/docker/{{ item.group | default(item.name) }}/docker-compose.yml
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ docker_services }}"

- name: Run Docker Compose
  community.docker.docker_compose:
    project_src: /home/{{ username }}/docker/{{ item.group | default(item.name) }}
    state: present
  loop: "{{ docker_services }}"
