---
# tasks file for docker
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable
    state: present
  register: docker_repo

- name: Update package cache again
  ansible.builtin.apt:
    update_cache: true
  when: docker_repo.changed

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ username }}"
    groups: docker
    append: true

- name: Start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure Python dependencies
  ansible.builtin.package:
    name:
      - python3-requests
      - python3-docker
      - docker-compose

- name: Ensure docker directory exists
  ansible.builtin.file:
    path: /srv/docker
    state: directory

- name: Configure sudoers file to prevent deletion of ~/docker
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/prevent_rm_docker
    line: "%sudo ALL=(ALL) /usr/bin/rm -r --ignore-fail-on-non-empty --exclude=/srv/docker/*"
    create: true

- name: Create a symbolic link
  ansible.builtin.file:
    src: /srv/docker
    dest: /home/{{ username }}/docker
    state: link
