---
# tasks file for docker
- name: Include docker tasks
  ansible.builtin.include_tasks: docker.yml

- name: Include docker compose tasks
  ansible.builtin.include_tasks: compose.yml
  when: docker_services is defined

- name: Include nginx tasks
  ansible.builtin.include_tasks: nginx.yml
  when: docker_services is defined
