---
- name: Install dependencies
  ansible.builtin.apt:
    state: absent
    name:
      - nginx

- name: Set IP address for service
  ansible.builtin.set_fact:
    host_ip: "{{ ansible_default_ipv4.address }}"

- include_role:
    name: add_service
  vars:
    service_ip: "{{ host_ip }}"
    service_name: "{{ item.name }}"
    service_alias: "{{ item.alias | default([]) }}"
    service_port: "{{ item.port }}"
    service_remote: "{{ item.remote | default(false) }}"
  loop: "{{ docker_services }}"

