---
ip_adress: "10.10.20.10"

docker_services:
  - name: adguard
    port: 3003

reverse_proxy:
  - name: router
    ip: 10.10.1.254
  - name: adguard2
    ip: 10.10.10.99
    port: 3004
  - name: synology
    ip: 10.10.10.99
    port: 5000
  - name: drive
    ip: 10.10.10.99
    port: 10002
  - name: photos
    ip: 10.10.10.99
    port: 5080
    remote: true
  - name: jenkins
    ip: 10.10.10.108
    port: 8080
  - name: home
    ip: 10.10.10.111
    port: 8123
  - name: octoprint
    ip: 10.10.10.248
  - name: proxmox-backup
    ip: 10.10.10.249
    port: 8007
    ssl: true
  - name: unifi
    ip: 10.10.10.254
    ssl: true
  - name: proxmox
    ip: 10.10.10.250
    port: 8006
    ssl: true
  - name: ansible
    ip: 10.10.20.35
    ssl: true

  # temporary
  - name: books
    ip: 10.10.20.20
    port: 13378
    remote: true
