---
- name: Perform DUO-related tasks
  block:
    - name: Copy custom DUO Login
      ansible.builtin.copy:
        src: usr/sbin/custom_duo_login
        dest: /usr/sbin/custom_duo_login

    - name: Create duosecurity.list file
      ansible.builtin.copy:
        content: deb [arch={{ ansible_architecture }}] https://pkg.duosecurity.com/{{ ansible_distribution }} {{ ansible_distribution_release }} main
        dest: /etc/apt/sources.list.d/duosecurity.list

    - name: Import DUO GPG public key
      ansible.builtin.apt_key:
        url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
        state: present

    - name: Update APT repositories
      ansible.builtin.apt:
        update_cache: true

    - name: Install duo-unix package
      ansible.builtin.apt:
        name: duo-unix
        state: present

  rescue:
    - name: Undo changes
      ansible.builtin.file:
        path: /usr/sbin/custom_duo_login
        state: absent

    - name: Remove duosecurity.list file
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/duosecurity.list
        state: absent

    - name: Remove DUO GPG public key
      ansible.builtin.apt_key:
        id: C927EBE00F1B0520
        state: absent

    - name: Remove duo-unix package
      ansible.builtin.apt:
        name: duo-unix
        state: absent
