---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - neovim
    - git
    - acl
    - tmux
    - neofetch
    - lolcat
    - toilet
    - cowsay
    - sl
    - exa
    - ripgrep
    - tldr
    - command-not-found
    - trash-cli
    - btop
    - bat
    - duf
    - python3
    - python3-pip
  ignore_errors: true

- name: Check if it's a VM
  ansible.builtin.command: systemd-detect-virt
  register: virt_detection
  ignore_errors: true
  changed_when: false

- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: "'kvm' in virt_detection.stdout"
