---
- name: Install packages
  ansible.builtin.apt:
    name:
      - vim
      - neovim
      - git
      - tmux
      - neofetch
      - lolcat
      - toilet
      - cowsay
      - sl
      - zoxide
      - exa
      - bat
      - duf
      - ripgrep
      - procs
      - tldr
      - btop
      - trash-cli
      - command-not-found
      - python3
      - python3-pip
    state: present
  tags: packages

- name: Check if it's a VM
  command: "systemd-detect-virt"
  register: virt_detection
  ignore_errors: true
  changed_when: false

- name: Install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  when: "'kvm' in virt_detection.stdout"
