---
- name: Install packages
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Install Ubuntu packages
  ansible.builtin.package:
    name: "{{ base_packages_ubuntu }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Install RHEL packages
  ansible.builtin.package:
    name: "{{ base_packages_rhel }}"
    state: present
  when: ansible_facts['os_family'] == 'RedHat'

- name: Check if it's a VM
  ansible.builtin.command: systemd-detect-virt
  register: virt_detection
  ignore_errors: true
  changed_when: false

- name: Install qemu-guest-agent
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: "'kvm' in virt_detection.stdout"
