---
- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ username }}/.oh-my-zsh
  become: true
  become_user: "{{ username }}"

- name: Install zsh-autosuggestions plugin
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: true
  become_user: "{{ username }}"

- name: Install zsh-syntax-highlight package
  ansible.builtin.apt:
    name: zsh-syntax-highlighting
    state: present

- name: Create zhrc file
  ansible.builtin.copy:
    src: home/zshrc
    dest: /home/{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Change user's shell to Zsh
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
