---
- name: Install Zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Clone Oh My Zsh repository
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/{{ username }}/.oh-my-zsh
  become: true
  become_user: "{{ username }}"

- name: Install plugins
  ansible.builtin.apt:
    name:
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: Create zhrc file
  ansible.builtin.copy:
    src: home/zshrc
    dest: /home/{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Change user's shell to Zsh
  ansible.builtin.user:
    name: "{{ username }}"
    shell: /bin/zsh
