---
- name: Remove authorized_keys for root
  ansible.builtin.file:
    path: /root/.ssh/authorized_keys
    state: absent

- name: Back up the original sshd_config
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak
    remote_src: true

- name: Perform SSH configuration changes
  block:
    - name: Disable root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^\s*#?\s*PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Disable SSH password authentication
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^\s*#?\s*PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Validate SSH server configuration
      ansible.builtin.shell:
        cmd: 'sshd -t'
      register: sshd_config_validation
      changed_when: false
      notify: Restart ssh

  rescue:
    - name: Display validation errors
      ansible.builtin.debug:
        msg: "{{ sshd_config_validation.stdout }}"
      when: sshd_config_validation.rc != 0

    - name: Restore original sshd_config
      ansible.builtin.copy:
        src: /etc/ssh/sshd_config.bak
        dest: /etc/ssh/sshd_config
        remote_src: true

  always:
    - name: Remove sshd_config.bak file
      ansible.builtin.file:
        path: /etc/ssh/sshd_config.bak
        state: absent

