---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"

- name: Ensure authorized_keys file exists
  ansible.builtin.file:
    path: /home/{{ username }}/.ssh/authorized_keys
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Add specific SSH key to authorized_keys
  ansible.builtin.lineinfile:
    path: /home/{{ username }}/.ssh/authorized_keys
    line: "{{ lookup('file', 'files/id_rsa.pub') }}"
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Create SSH config file
  ansible.builtin.copy:
    src: ssh_config
    dest: /home/{{ username }}/.ssh/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Remove authorized_keys for root
  file:
    path: /root/.ssh/authorized_keys
    state: absent
