---
- name: Create user
  ansible.builtin.user:
    name: "{{ username }}"
    state: present
    createhome: true

- name: Create system user mediamanager
  ansible.builtin.user:
    name: mediamanager
    uid: 1080
    system: true
  when: mount_media is defined and mount_media

- name: Add passwordless sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ username }}
    state: present
    create: true
    mode: "0440"
    line: "{{ username }} ALL=(ALL:ALL) NOPASSWD:ALL"
    validate: /usr/sbin/visudo -cf %s
