---
- name: Install NVIDIA driver, CUDA, nvidia-smi, nvidia-settings
  ansible.builtin.apt:
    name:
      - linux-headers-generic
    state: present

- name: Install GPU drivers with ubuntu-drivers
  ansible.builtin.command: ubuntu-drivers autoinstall
  changed_when: false

- name: Test nvidia drivers
  ansible.builtin.command: nvidia-smi
  changed_when: false
