---
- name: Check if swapfile exists
  ansible.builtin.stat:
    path: /swapfile
  register: swapfile_stat

- name: Create swapfile if it doesn't exist
  ansible.builtin.command: fallocate -l 16G /swapfile
  when: not swapfile_stat.stat.exists

- name: Set permissions on swapfile
  ansible.builtin.file:
    path: /swapfile
    mode: "0600"
  when: not swapfile_stat.stat.exists

- name: Make swap space
  ansible.builtin.command: mkswap /swapfile
  when: not swapfile_stat.stat.exists

- name: Enable swapfile
  ansible.builtin.command: swapon /swapfile
  when: not swapfile_stat.stat.exists

- name: Add swapfile to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: /swapfile none swap sw 0 0
  when: not swapfile_stat.stat.exists

- name: Ensure swap is active
  ansible.builtin.command: swapon --show
  changed_when: false
